CREATE TABLE IF NOT EXISTS person (
    id INTEGER PRIMARY KEY,
    user TEXT NOT NULL,
    pass TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "transaction" (
    hash TEXT NOT NULL PRIMARY KEY,
    date TEXT NOT NULL DEFAULT CURRENT_DATE,
    time TEXT NOT NULL DEFAULT CURRENT_TIME,
    message TEXT NOT NULL,
    amount REAL NOT NULL,
    person INTEGER NOT NULL REFERENCES person (id)
);
